### ISSUE TITLE
BB logging is not real-time; logging sometimes lost if BB crashes

### ISSUE THREAD

**Issue by hlygrail** [maxcom99/brokenbot-support#14]
Short version:   http://nlog-project.org/ 

Long version:  Logging in BB needs some help.  Seems like there's some caching of to-be-logged data, and it either doesn't land in the file real-time (or the log file is op-locked or something), or if BB crashes, it may NEVER get written.

Need to deploy some better logging solution, and I understand nlog is pretty much free...

**Comment by codebroken** [comment]
We already use something similar to n-log.  The not realtime nature of the logging is very intentional because we don't want slow I/O slowing the bot down.  If the bot experiences a crash it makes its best effort at prioritizing writing the log to the file.  Some crashes prevent this - finding the root of these crashes is high priority of course.
